CREATE DATABASE BOOKMAN
GO
USE BOOKMAN
GO
CREATE TABLE BOOK
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(50),
	AUTHORS NVARCHAR(50),
	PUBLISHER NVARCHAR(50),
	YEAR INT NOT NULL,
	DESCRIPTION NVARCHAR(200),
	DATAFILE VARCHAR(100)
)